// Code generated by internal/generate/capabilities.py; DO NOT EDIT.
package firebirdotel

import (
	"database/sql/driver"
	"reflect"
)

type RowsColumnTypeScanTypeMethods interface{ ColumnTypeScanType(int) reflect.Type }
type RowsColumnTypePrecisionScaleMethods interface {
	ColumnTypePrecisionScale(int) (int64, int64, bool)
}
type RowsColumnTypeNullableMethods interface{ ColumnTypeNullable(int) (bool, bool) }
type RowsColumnTypeLengthMethods interface{ ColumnTypeLength(int) (int64, bool) }
type RowsColumnTypeDatabaseTypeNameMethods interface{ ColumnTypeDatabaseTypeName(int) string }
type RowsNextResultSetMethods interface {
	HasNextResultSet() bool
	NextResultSet() error
}

func wrapRows(s *rowsState) driver.Rows {
	mask := 0
	if _, ok := s.raw.(driver.RowsNextResultSet); ok {
		mask |= 1
	}
	if _, ok := s.raw.(driver.RowsColumnTypeDatabaseTypeName); ok {
		mask |= 2
	}
	if _, ok := s.raw.(driver.RowsColumnTypeLength); ok {
		mask |= 4
	}
	if _, ok := s.raw.(driver.RowsColumnTypeNullable); ok {
		mask |= 8
	}
	if _, ok := s.raw.(driver.RowsColumnTypePrecisionScale); ok {
		mask |= 16
	}
	if _, ok := s.raw.(driver.RowsColumnTypeScanType); ok {
		mask |= 32
	}
	switch mask {
	case 0:
		return struct{ rowsBase }{s}
	case 1:
		return struct {
			rowsBase
			RowsNextResultSetMethods
		}{s, s}
	case 2:
		return struct {
			rowsBase
			RowsColumnTypeDatabaseTypeNameMethods
		}{s, s}
	case 3:
		return struct {
			rowsBase
			RowsNextResultSetMethods
			RowsColumnTypeDatabaseTypeNameMethods
		}{s, s, s}
	case 4:
		return struct {
			rowsBase
			RowsColumnTypeLengthMethods
		}{s, s}
	case 5:
		return struct {
			rowsBase
			RowsNextResultSetMethods
			RowsColumnTypeLengthMethods
		}{s, s, s}
	case 6:
		return struct {
			rowsBase
			RowsColumnTypeDatabaseTypeNameMethods
			RowsColumnTypeLengthMethods
		}{s, s, s}
	case 7:
		return struct {
			rowsBase
			RowsNextResultSetMethods
			RowsColumnTypeDatabaseTypeNameMethods
			RowsColumnTypeLengthMethods
		}{s, s, s, s}
	case 8:
		return struct {
			rowsBase
			RowsColumnTypeNullableMethods
		}{s, s}
	case 9:
		return struct {
			rowsBase
			RowsNextResultSetMethods
			RowsColumnTypeNullableMethods
		}{s, s, s}
	case 10:
		return struct {
			rowsBase
			RowsColumnTypeDatabaseTypeNameMethods
			RowsColumnTypeNullableMethods
		}{s, s, s}
	case 11:
		return struct {
			rowsBase
			RowsNextResultSetMethods
			RowsColumnTypeDatabaseTypeNameMethods
			RowsColumnTypeNullableMethods
		}{s, s, s, s}
	case 12:
		return struct {
			rowsBase
			RowsColumnTypeLengthMethods
			RowsColumnTypeNullableMethods
		}{s, s, s}
	case 13:
		return struct {
			rowsBase
			RowsNextResultSetMethods
			RowsColumnTypeLengthMethods
			RowsColumnTypeNullableMethods
		}{s, s, s, s}
	case 14:
		return struct {
			rowsBase
			RowsColumnTypeDatabaseTypeNameMethods
			RowsColumnTypeLengthMethods
			RowsColumnTypeNullableMethods
		}{s, s, s, s}
	case 15:
		return struct {
			rowsBase
			RowsNextResultSetMethods
			RowsColumnTypeDatabaseTypeNameMethods
			RowsColumnTypeLengthMethods
			RowsColumnTypeNullableMethods
		}{s, s, s, s, s}
	case 16:
		return struct {
			rowsBase
			RowsColumnTypePrecisionScaleMethods
		}{s, s}
	case 17:
		return struct {
			rowsBase
			RowsNextResultSetMethods
			RowsColumnTypePrecisionScaleMethods
		}{s, s, s}
	case 18:
		return struct {
			rowsBase
			RowsColumnTypeDatabaseTypeNameMethods
			RowsColumnTypePrecisionScaleMethods
		}{s, s, s}
	case 19:
		return struct {
			rowsBase
			RowsNextResultSetMethods
			RowsColumnTypeDatabaseTypeNameMethods
			RowsColumnTypePrecisionScaleMethods
		}{s, s, s, s}
	case 20:
		return struct {
			rowsBase
			RowsColumnTypeLengthMethods
			RowsColumnTypePrecisionScaleMethods
		}{s, s, s}
	case 21:
		return struct {
			rowsBase
			RowsNextResultSetMethods
			RowsColumnTypeLengthMethods
			RowsColumnTypePrecisionScaleMethods
		}{s, s, s, s}
	case 22:
		return struct {
			rowsBase
			RowsColumnTypeDatabaseTypeNameMethods
			RowsColumnTypeLengthMethods
			RowsColumnTypePrecisionScaleMethods
		}{s, s, s, s}
	case 23:
		return struct {
			rowsBase
			RowsNextResultSetMethods
			RowsColumnTypeDatabaseTypeNameMethods
			RowsColumnTypeLengthMethods
			RowsColumnTypePrecisionScaleMethods
		}{s, s, s, s, s}
	case 24:
		return struct {
			rowsBase
			RowsColumnTypeNullableMethods
			RowsColumnTypePrecisionScaleMethods
		}{s, s, s}
	case 25:
		return struct {
			rowsBase
			RowsNextResultSetMethods
			RowsColumnTypeNullableMethods
			RowsColumnTypePrecisionScaleMethods
		}{s, s, s, s}
	case 26:
		return struct {
			rowsBase
			RowsColumnTypeDatabaseTypeNameMethods
			RowsColumnTypeNullableMethods
			RowsColumnTypePrecisionScaleMethods
		}{s, s, s, s}
	case 27:
		return struct {
			rowsBase
			RowsNextResultSetMethods
			RowsColumnTypeDatabaseTypeNameMethods
			RowsColumnTypeNullableMethods
			RowsColumnTypePrecisionScaleMethods
		}{s, s, s, s, s}
	case 28:
		return struct {
			rowsBase
			RowsColumnTypeLengthMethods
			RowsColumnTypeNullableMethods
			RowsColumnTypePrecisionScaleMethods
		}{s, s, s, s}
	case 29:
		return struct {
			rowsBase
			RowsNextResultSetMethods
			RowsColumnTypeLengthMethods
			RowsColumnTypeNullableMethods
			RowsColumnTypePrecisionScaleMethods
		}{s, s, s, s, s}
	case 30:
		return struct {
			rowsBase
			RowsColumnTypeDatabaseTypeNameMethods
			RowsColumnTypeLengthMethods
			RowsColumnTypeNullableMethods
			RowsColumnTypePrecisionScaleMethods
		}{s, s, s, s, s}
	case 31:
		return struct {
			rowsBase
			RowsNextResultSetMethods
			RowsColumnTypeDatabaseTypeNameMethods
			RowsColumnTypeLengthMethods
			RowsColumnTypeNullableMethods
			RowsColumnTypePrecisionScaleMethods
		}{s, s, s, s, s, s}
	case 32:
		return struct {
			rowsBase
			RowsColumnTypeScanTypeMethods
		}{s, s}
	case 33:
		return struct {
			rowsBase
			RowsNextResultSetMethods
			RowsColumnTypeScanTypeMethods
		}{s, s, s}
	case 34:
		return struct {
			rowsBase
			RowsColumnTypeDatabaseTypeNameMethods
			RowsColumnTypeScanTypeMethods
		}{s, s, s}
	case 35:
		return struct {
			rowsBase
			RowsNextResultSetMethods
			RowsColumnTypeDatabaseTypeNameMethods
			RowsColumnTypeScanTypeMethods
		}{s, s, s, s}
	case 36:
		return struct {
			rowsBase
			RowsColumnTypeLengthMethods
			RowsColumnTypeScanTypeMethods
		}{s, s, s}
	case 37:
		return struct {
			rowsBase
			RowsNextResultSetMethods
			RowsColumnTypeLengthMethods
			RowsColumnTypeScanTypeMethods
		}{s, s, s, s}
	case 38:
		return struct {
			rowsBase
			RowsColumnTypeDatabaseTypeNameMethods
			RowsColumnTypeLengthMethods
			RowsColumnTypeScanTypeMethods
		}{s, s, s, s}
	case 39:
		return struct {
			rowsBase
			RowsNextResultSetMethods
			RowsColumnTypeDatabaseTypeNameMethods
			RowsColumnTypeLengthMethods
			RowsColumnTypeScanTypeMethods
		}{s, s, s, s, s}
	case 40:
		return struct {
			rowsBase
			RowsColumnTypeNullableMethods
			RowsColumnTypeScanTypeMethods
		}{s, s, s}
	case 41:
		return struct {
			rowsBase
			RowsNextResultSetMethods
			RowsColumnTypeNullableMethods
			RowsColumnTypeScanTypeMethods
		}{s, s, s, s}
	case 42:
		return struct {
			rowsBase
			RowsColumnTypeDatabaseTypeNameMethods
			RowsColumnTypeNullableMethods
			RowsColumnTypeScanTypeMethods
		}{s, s, s, s}
	case 43:
		return struct {
			rowsBase
			RowsNextResultSetMethods
			RowsColumnTypeDatabaseTypeNameMethods
			RowsColumnTypeNullableMethods
			RowsColumnTypeScanTypeMethods
		}{s, s, s, s, s}
	case 44:
		return struct {
			rowsBase
			RowsColumnTypeLengthMethods
			RowsColumnTypeNullableMethods
			RowsColumnTypeScanTypeMethods
		}{s, s, s, s}
	case 45:
		return struct {
			rowsBase
			RowsNextResultSetMethods
			RowsColumnTypeLengthMethods
			RowsColumnTypeNullableMethods
			RowsColumnTypeScanTypeMethods
		}{s, s, s, s, s}
	case 46:
		return struct {
			rowsBase
			RowsColumnTypeDatabaseTypeNameMethods
			RowsColumnTypeLengthMethods
			RowsColumnTypeNullableMethods
			RowsColumnTypeScanTypeMethods
		}{s, s, s, s, s}
	case 47:
		return struct {
			rowsBase
			RowsNextResultSetMethods
			RowsColumnTypeDatabaseTypeNameMethods
			RowsColumnTypeLengthMethods
			RowsColumnTypeNullableMethods
			RowsColumnTypeScanTypeMethods
		}{s, s, s, s, s, s}
	case 48:
		return struct {
			rowsBase
			RowsColumnTypePrecisionScaleMethods
			RowsColumnTypeScanTypeMethods
		}{s, s, s}
	case 49:
		return struct {
			rowsBase
			RowsNextResultSetMethods
			RowsColumnTypePrecisionScaleMethods
			RowsColumnTypeScanTypeMethods
		}{s, s, s, s}
	case 50:
		return struct {
			rowsBase
			RowsColumnTypeDatabaseTypeNameMethods
			RowsColumnTypePrecisionScaleMethods
			RowsColumnTypeScanTypeMethods
		}{s, s, s, s}
	case 51:
		return struct {
			rowsBase
			RowsNextResultSetMethods
			RowsColumnTypeDatabaseTypeNameMethods
			RowsColumnTypePrecisionScaleMethods
			RowsColumnTypeScanTypeMethods
		}{s, s, s, s, s}
	case 52:
		return struct {
			rowsBase
			RowsColumnTypeLengthMethods
			RowsColumnTypePrecisionScaleMethods
			RowsColumnTypeScanTypeMethods
		}{s, s, s, s}
	case 53:
		return struct {
			rowsBase
			RowsNextResultSetMethods
			RowsColumnTypeLengthMethods
			RowsColumnTypePrecisionScaleMethods
			RowsColumnTypeScanTypeMethods
		}{s, s, s, s, s}
	case 54:
		return struct {
			rowsBase
			RowsColumnTypeDatabaseTypeNameMethods
			RowsColumnTypeLengthMethods
			RowsColumnTypePrecisionScaleMethods
			RowsColumnTypeScanTypeMethods
		}{s, s, s, s, s}
	case 55:
		return struct {
			rowsBase
			RowsNextResultSetMethods
			RowsColumnTypeDatabaseTypeNameMethods
			RowsColumnTypeLengthMethods
			RowsColumnTypePrecisionScaleMethods
			RowsColumnTypeScanTypeMethods
		}{s, s, s, s, s, s}
	case 56:
		return struct {
			rowsBase
			RowsColumnTypeNullableMethods
			RowsColumnTypePrecisionScaleMethods
			RowsColumnTypeScanTypeMethods
		}{s, s, s, s}
	case 57:
		return struct {
			rowsBase
			RowsNextResultSetMethods
			RowsColumnTypeNullableMethods
			RowsColumnTypePrecisionScaleMethods
			RowsColumnTypeScanTypeMethods
		}{s, s, s, s, s}
	case 58:
		return struct {
			rowsBase
			RowsColumnTypeDatabaseTypeNameMethods
			RowsColumnTypeNullableMethods
			RowsColumnTypePrecisionScaleMethods
			RowsColumnTypeScanTypeMethods
		}{s, s, s, s, s}
	case 59:
		return struct {
			rowsBase
			RowsNextResultSetMethods
			RowsColumnTypeDatabaseTypeNameMethods
			RowsColumnTypeNullableMethods
			RowsColumnTypePrecisionScaleMethods
			RowsColumnTypeScanTypeMethods
		}{s, s, s, s, s, s}
	case 60:
		return struct {
			rowsBase
			RowsColumnTypeLengthMethods
			RowsColumnTypeNullableMethods
			RowsColumnTypePrecisionScaleMethods
			RowsColumnTypeScanTypeMethods
		}{s, s, s, s, s}
	case 61:
		return struct {
			rowsBase
			RowsNextResultSetMethods
			RowsColumnTypeLengthMethods
			RowsColumnTypeNullableMethods
			RowsColumnTypePrecisionScaleMethods
			RowsColumnTypeScanTypeMethods
		}{s, s, s, s, s, s}
	case 62:
		return struct {
			rowsBase
			RowsColumnTypeDatabaseTypeNameMethods
			RowsColumnTypeLengthMethods
			RowsColumnTypeNullableMethods
			RowsColumnTypePrecisionScaleMethods
			RowsColumnTypeScanTypeMethods
		}{s, s, s, s, s, s}
	case 63:
		return struct {
			rowsBase
			RowsNextResultSetMethods
			RowsColumnTypeDatabaseTypeNameMethods
			RowsColumnTypeLengthMethods
			RowsColumnTypeNullableMethods
			RowsColumnTypePrecisionScaleMethods
			RowsColumnTypeScanTypeMethods
		}{s, s, s, s, s, s, s}
	default:
		panic("unreachable capability mask")
	}
}
