// Code generated by internal/generate/capabilities.py; DO NOT EDIT.
package firebirdotel

import "database/sql/driver"

func wrapStmt(s *stmtState) driver.Stmt {
	mask := 0
	if _, ok := s.raw.(driver.StmtExecContext); ok {
		mask |= 1
	}
	if _, ok := s.raw.(driver.StmtQueryContext); ok {
		mask |= 2
	}
	if _, ok := s.raw.(driver.ColumnConverter); ok {
		mask |= 4
	}
	if _, ok := s.raw.(driver.NamedValueChecker); ok {
		mask |= 8
	}
	switch mask {
	case 0:
		return struct{ stmtBase }{s}
	case 1:
		return struct {
			stmtBase
			driver.StmtExecContext
		}{s, s}
	case 2:
		return struct {
			stmtBase
			driver.StmtQueryContext
		}{s, s}
	case 3:
		return struct {
			stmtBase
			driver.StmtExecContext
			driver.StmtQueryContext
		}{s, s, s}
	case 4:
		return struct {
			stmtBase
			driver.ColumnConverter
		}{s, s}
	case 5:
		return struct {
			stmtBase
			driver.StmtExecContext
			driver.ColumnConverter
		}{s, s, s}
	case 6:
		return struct {
			stmtBase
			driver.StmtQueryContext
			driver.ColumnConverter
		}{s, s, s}
	case 7:
		return struct {
			stmtBase
			driver.StmtExecContext
			driver.StmtQueryContext
			driver.ColumnConverter
		}{s, s, s, s}
	case 8:
		return struct {
			stmtBase
			driver.NamedValueChecker
		}{s, s}
	case 9:
		return struct {
			stmtBase
			driver.StmtExecContext
			driver.NamedValueChecker
		}{s, s, s}
	case 10:
		return struct {
			stmtBase
			driver.StmtQueryContext
			driver.NamedValueChecker
		}{s, s, s}
	case 11:
		return struct {
			stmtBase
			driver.StmtExecContext
			driver.StmtQueryContext
			driver.NamedValueChecker
		}{s, s, s, s}
	case 12:
		return struct {
			stmtBase
			driver.ColumnConverter
			driver.NamedValueChecker
		}{s, s, s}
	case 13:
		return struct {
			stmtBase
			driver.StmtExecContext
			driver.ColumnConverter
			driver.NamedValueChecker
		}{s, s, s, s}
	case 14:
		return struct {
			stmtBase
			driver.StmtQueryContext
			driver.ColumnConverter
			driver.NamedValueChecker
		}{s, s, s, s}
	case 15:
		return struct {
			stmtBase
			driver.StmtExecContext
			driver.StmtQueryContext
			driver.ColumnConverter
			driver.NamedValueChecker
		}{s, s, s, s, s}
	default:
		panic("unreachable capability mask")
	}
}
