#!/usr/bin/env python3
"""Generate exact optional-interface method sets. Do not hand-edit the output.

Interface fields expose only the selected methods of each state object; the
base interface prevents all the other optional state methods leaking through.
This preserves database/sql's own named-value and context fallback decisions.
"""
from pathlib import Path
import subprocess
specs = {
 'Conn': ['ConnPrepareContext','ConnBeginTx','Execer','ExecerContext','Queryer','QueryerContext','Pinger','SessionResetter','Validator','NamedValueChecker'],
 'Stmt': ['StmtExecContext','StmtQueryContext','ColumnConverter','NamedValueChecker'],
 'Rows': ['RowsNextResultSet','RowsColumnTypeDatabaseTypeName','RowsColumnTypeLength','RowsColumnTypeNullable','RowsColumnTypePrecisionScale','RowsColumnTypeScanType'],
}
for name, optional in specs.items():
 lower=name.lower()
 lines=['// Code generated by internal/generate/capabilities.py; DO NOT EDIT.','package firebirdotel','import "database/sql/driver"',f'func wrap{name}(s *{lower}State) driver.{name} {{','mask:=0']
 for i, interface in enumerate(optional):
  lines.append(f'if _,ok:=s.raw.(driver.{interface});ok {{mask|={1<<i}}}')
 if name == 'Rows':
  lines[2]='import ("database/sql/driver";"reflect")'
  methods=['HasNextResultSet() bool;NextResultSet() error','ColumnTypeDatabaseTypeName(int) string','ColumnTypeLength(int)(int64,bool)','ColumnTypeNullable(int)(bool,bool)','ColumnTypePrecisionScale(int)(int64,int64,bool)','ColumnTypeScanType(int) reflect.Type']
  for interface, method in zip(optional,methods):
   lines.insert(3,f'type {interface}Methods interface{{{method}}}')
 lines.append('switch mask {')
 for mask in range(1<<len(optional)):
  selected=[v for i,v in enumerate(optional) if mask&(1<<i)]
  fields=';'.join([f'{lower}Base']+[(v+'Methods' if name=='Rows' else 'driver.'+v) for v in selected])
  values=','.join(['s']*(len(selected)+1))
  lines.append(f'case {mask}: return struct{{{fields}}}{{{values}}}')
 lines+=['default: panic("unreachable capability mask")','}','}']
 Path(f'capabilities_{lower}_generated.go').write_text('\n'.join(lines)+'\n')

subprocess.run(["gofmt", "-w", *[f"capabilities_{name.lower()}_generated.go" for name in specs]], check=True)
